### ISSUE TITLE
Document use of Azure Managed Identities for AzureDNS

### ISSUE THREAD

**Issue by riccardodl** [cert-manager/website#328]
**Is your feature request related to a problem? Please describe.**

Support for Azure managed identities was added by this pull request and added to release [0.15.0](https://github.com/jetstack/cert-manager/releases/tag/v0.15.0). Unfortunately there is no documentation regarding use of MSI in the [official docs](https://cert-manager.io/docs/configuration/acme/dns01/azuredns/). I went looking around and I found that the original contributor @gitirabassi of the aforementioned MR wrote some [documentation](https://github.com/gitirabassi/website/blob/feat/azure-auth-msi-master/content/en/docs/configuration/acme/dns01/azuredns.md#managed-identity), but for whatever reason this was not merged back into master.

Moreover, the way the original contrib. explains the way this feature works contrasts the way pod-identity (which is instrumental for the feature to work) wants to define the identity bindings ( i.e. one says that `aadpodidbinding:<value>` should be ["cert-manager"](https://github.com/gitirabassi/website/blob/feat/azure-auth-msi-master/content/en/docs/configuration/acme/dns01/azuredns.md#managed-identity) vs. the other says it should be [$IDENTITY_NAME](https://github.com/Azure/aad-pod-identity#6-deployment-and-validation) aka. the MSI name) of course the maintainers of this repo cannot be responsible for the claim, since it is not in the official docs, still, I would ask if there is anyone that can dispel the confusion.

Is there someone who knows exactly how using managed identities works? Can we work together to document the feature?
In my case I would actually like to use multiple managed identities for different ClusterIssuers, or at the very least, use a different one rather than the omsagent MSI to modify my DNS records, do we know if this is possible to do at all?

**Describe the solution you'd like**
I see that the documentation [MR](https://github.com/cert-manager/website/pull/148) containing the aforementioned documentation for use of MSI has been opened in March and has recently received some love. The example though only refers to a terraform example, I would appreciate it helm install/static manifests are added too.

**Describe alternatives you've considered**
I've considered bypassing managed identities assignment using pod identity, by generating an MSI (using an ARM template) and then accessing the underlying service principal, and then giving the SP credentials to cert-manager via secret. Unfortunately it is not possible to access SP credentials after it has been created. The only time when those are returned is when an SP is created directly through az cli.

**Additional context**
Based from #3148 I can see that maybe there is also an issue if you have multiple MSI defined in the target resource group where AKS (and therefore pod identity is defined), can someone confirm this? The fact that you cannot define the name of the MSI you want to target seems to be a feature that could indeed be added (or is this an hint that `aadpodidbinding:???` should contain the `$IDENTITY_NAME`?)

**Environment details (if applicable)**:
- Kubernetes version (e.g. v1.10.2): 1.18.6
- Cloud-provider/provisioner (e.g. GKE, kops AWS, etc): Azure
- cert-manager version (e.g. v0.4.0): 1.0.0
- Install method (e.g. helm or static manifests): helm

/kind documentation
/triage support

**Comment by JasonWhall** [comment]
@riccardodl - I've raised a [PR](#350) to help add this documentation which adds an example setup. Let me know if you would like to add anything?

**Comment by calexandre** [comment]
It would be awesome to use the built-in kubelet identity for an AKS cluster. I've already [mentioned this on your PR](https://github.com/cert-manager/website/pull/350#issuecomment-729262595) @JasonWhall ;)

**Comment by calexandre** [comment]
So, following [this discussion](https://github.com/cert-manager/website/pull/350#issuecomment-729262595) regarding the use of the managed Kubelet identity on an AKS cluster, I managed to deploy `cert-manager` using the managed Kubelet identity but with one caveat.

Note that this setup option, dismisses the use of [AAD Pod Identity](https://azure.github.io/aad-pod-identity).

The caveat is that there is no place to define which managed identity `clientId` to use - similar deployments like `external-dns` fixed this by adding an option to specify the `userAssignedIdentityID`.
While it does work using a default AKS cluster, once you add another identity to the Kubelet resource group, it won't work - which will happen if you enable the `kube_dashboard` addon for instance, because Azure will provision a dedicated identity for that particular deployment.

This is the `ClusterIssuer` I'm using:

```yaml
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: something@nowhere.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        azuredns:
          subscriptionID: subscription-id
          resourceGroupName: dns-resource-group
          hostedZoneName: dns-zone-name
          environment: AzurePublicCloud
```

**Comment by JasonWhall** [comment]
Thanks @calexandre! I've updated the PR to add some notes to reflect this.

**Comment by ryanjn** [comment]
@calexandre I've been trying this with an almost identical setup, sans that my cluster is private.  But cert-manager is unable to get authorization with azureDNS.

```
cert-manager/controller/challenges "msg"="re-queuing item due to error processing" "error"="azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/[redacted subscription id]/resourceGroups/rg-k8s-apps/providers/Microsoft.Network/dnsZones/[redacted domain]/TXT/_acme-challenge?api-version=2017-10-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"Identity not found\"}" "key"="cert-manager/acme-cert-manager-config-jspsl-1663922252-721872768"
```

I have disabled the `kube_dasboard` add-on, but the issue still persists.

Config excerpt:

```
resource "azurerm_kubernetes_cluster" "k8s" {
  name                    = "aks-${var.cluster_name}"
  location                = var.resource_group.location
  resource_group_name     = var.resource_group.name
  dns_prefix              = var.cluster_name
  private_cluster_enabled = true
  kubernetes_version      = var.kubernetes_version

  role_based_access_control {
    enabled                   = true
    azure_active_directory {
      managed                   = true
      admin_group_object_ids    = [ azuread_group.cluster_admin.id ]
    }
  }

  default_node_pool {
    name                  = "default"
    enable_auto_scaling   = true
    min_count             = var.node_pool_min_size
    max_count             = var.node_pool_max_size
    vm_size               = var.node_pool_vm_size
    vnet_subnet_id        = var.kube_subnet.id
    orchestrator_version  = var.kubernetes_version
    availability_zones    = var.availability_zones
  }

  identity {
    type = "SystemAssigned"
  }

  node_resource_group =       "rg-${var.cluster_name}-k8s-nodes"

  linux_profile {
    admin_username           = "${var.cluster_name}-admin"
    ssh_key {
      key_data               = azurerm_key_vault_secret.cluster_publickey.value
    }
  }

  addon_profile {
    kube_dashboard {
      enabled               = var.enable_dashboard  // false
    }
  }

  network_profile {
    network_plugin            = "azure"
    outbound_type             = "userDefinedRouting"
  }

  depends_on = [ azurerm_route_table.rt ]
}

resource "azurerm_role_assignment" "domain_manager" {
  scope                            = var.cluster_dns_zone.id
  role_definition_name             = "DNS Zone Contributor"
  principal_id                     = azurerm_kubernetes_cluster.k8s.kubelet_identity[0].object_id
  skip_service_principal_aad_check = true
}
```

I've drained and restarted the node, just in case, but to no avail.  I too encountered this issue with `external-dns` and used the `userAssignedIdentityID` to fix this there, but without that workaround available here - i'm stuck.

**Comment by calexandre** [comment]
@ryanjn did you check the resource-group that Azure creates for managing AKS related entities? If you find more than one managed identity that might be the issue - only the `agentpool` identity should be present.

Try to re-create the entire thing without the `kube-dashboard` and see if it works..

**Comment by ppanyukov** [comment]
Hey @calexandre do you have a link to `external-dns` repo, I want to see how they implemented `userAssignedIdentityID` there and perhaps try to borrow it for `cert-manager`.

**Comment by JasonWhall** [comment]
@ppanyukov you should find the auth implementation for external-dns here - https://github.com/kubernetes-sigs/external-dns/blob/ae1054519c9cb8f2ff4c80d5a555f0c46794a14c/provider/azure/config.go#L79

**Comment by evmimagina** [comment]
Hi,

Any updates on this?

Thanks and regards,

**Comment by sebader** [comment]
I landed here as well with the same issue. We are using kube_dashboard and hence have the `omsagent` Identity assigned to the nodes as well. Thus we cannot use cert-manager with Azure DNS and MSI for now :( would be great if support for selecting the right identity could be added!
